source 'http://rubygems.org'
gem 'activerecord', '~> 5.2', '>= 5.2.2.1', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3', '~>1.3.6'
gem 'sinatra'
gem 'thin'
gem 'shotgun'
gem 'tux'
gem 'pry'
gem 'rake'
gem 'sinatra-twitter-bootstrap', :require => 'sinatra/twitter-bootstrap'
gem 'require_all'
gem 'sinatra-flash'
gem 'rack-flash3'
gem 'bcrypt'
group :test do
  gem 'launchy'
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner'
end